# Conversion
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
        disable: true
defaults:
     - scope:
           path: /main/
       values:
           permalink: /:title/
           layout: default-md
     - scope:
           path: /wiki/
       values:
           layout: wiki

